interface Product {
    id: string;
    name: string;
    imageUrl: string;
    description: string;
    price: number;
    salePrice?: number;
    isOnSale: boolean;
    isInStock: boolean;
    gameType: 'RS3' | 'OSRS' | 'WOW';
    itemType: string;
  }
  
  // Mock data
  const mockProducts: Product[] = [
    {
      id: '1',
      name: 'Dragon Dagger',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/6e9f4fb1-0ee2-41a9-8ed9-cee200127a9e',
      description: 'A powerful melee weapon for close combat.',
      price: 45.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '2',
      name: 'Bandos Chestplate',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/d4b6bd53-c47e-48da-aef0-8c6b91d734a4',
      description: 'High-level melee armor offering great protection.',
      price: 85.00,
      salePrice: 75.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'armor'
    },
    {
      id: '3',
      name: 'Super Combat Potion Pack',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Bundle of combat-enhancing potions.',
      price: 35.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'consumable'
    },
    {
      id: '4',
      name: 'Noxious Scythe',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Powerful two-handed weapon with great reach.',
      price: 250.00,
      salePrice: 225.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'weapon'
    },
    {
      id: '5',
      name: 'Torva Platebody',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Elite-tier melee armor.',
      price: 180.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'armor'
    },
    {
      id: '6',
      name: 'Overload Potion Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Premium combat enhancement potions.',
      price: 65.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'consumable'
    },
    {
      id: '7',
      name: 'Shadowmourne',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Legendary battle axe of immense power.',
      price: 450.00,
      salePrice: 399.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'weapon'
    },
    {
      id: '8',
      name: 'Celestial Plate Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Mythic-level protective armor set.',
      price: 299.99,
      isOnSale: false,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'armor'
    },
    {
      id: '9',
      name: 'Flask of Power Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Set of powerful combat and utility potions.',
      price: 25.00,
      salePrice: 20.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'consumable'
    },
    {
      id: '10',
      name: 'Abyssal Whip',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Fast attacking melee weapon.',
      price: 95.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '11',
      name: 'Armadyl Godsword',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Legendary godsword with devastating special attack.',
      price: 175.00,
      salePrice: 150.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '12',
      name: 'Primordial Boots',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/d4b6bd53-c47e-48da-aef0-8c6b91d734a4',
      description: 'Best-in-slot melee boots.',
      price: 120.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'armor'
    },
    {
      id: '13',
      name: 'Divine Super Combat Pack',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Enhanced combat potions with divine effects.',
      price: 45.00,
      salePrice: 35.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'consumable'
    },
    {
      id: '14',
      name: 'Drygore Longsword',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'High-tier melee weapon for advanced combat.',
      price: 195.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'weapon'
    },
    {
      id: '15',
      name: 'Malevolent Armor Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Superior degradeable power armor.',
      price: 280.00,
      salePrice: 250.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'armor'
    },
    {
      id: '16',
      name: 'Elder Overload Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Supreme combat enhancement potions.',
      price: 85.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'consumable'
    },
    {
      id: '17',
      name: 'Thunderfury',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Legendary sword of the Windseeker.',
      price: 550.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'weapon'
    },
    {
      id: '18',
      name: 'Tier 20 Armor Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Classic raid tier armor set.',
      price: 375.00,
      salePrice: 325.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'armor'
    },
    {
      id: '19',
      name: 'Mythic+ Potion Kit',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Essential potions for high-level dungeons.',
      price: 40.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'consumable'
    },
    {
      id: '20',
      name: 'Twisted Bow',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Powerful bow effective against magical creatures.',
      price: 850.00,
      salePrice: 799.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '21',
      name: 'Ancestral Robe Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Best-in-slot magic armor.',
      price: 275.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'armor'
    },
    {
      id: '22',
      name: 'Raids Potion Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Complete set of raiding potions.',
      price: 55.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'consumable'
    },
    {
      id: '23',
      name: 'Staff of Sliske',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Powerful magic staff with special effects.',
      price: 420.00,
      salePrice: 375.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'weapon'
    },
    {
      id: '24',
      name: 'Trimmed Masterwork Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Best-in-slot melee armor.',
      price: 450.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'armor'
    },
    {
      id: '25',
      name: 'Supreme Raid Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Complete pack of high-tier consumables.',
      price: 95.00,
      salePrice: 85.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'consumable'
    },
    {
      id: '26',
      name: 'Frostmourne Replica',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Legendary sword of the Lich King.',
      price: 750.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'weapon'
    },
    {
      id: '27',
      name: 'Mythic Raid Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Current tier mythic raid armor.',
      price: 425.00,
      salePrice: 399.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'armor'
    },
    {
      id: '28',
      name: 'Raid Ready Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Complete set of raiding consumables.',
      price: 75.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'consumable'
    },
    {
      id: '29',
      name: 'Eldritch Crossbow',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Elite ranged weapon with special effect.',
      price: 650.00,
      salePrice: 599.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'weapon'
    },
    {
      id: '30',
      name: 'Inquisitor Armor Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Powerful crush-bonus armor set.',
      price: 395.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'armor'
    },
    {
      id: '31',
      name: 'Infernal Cape Service',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Prestigious cape showing PvM mastery.',
      price: 299.99,
      salePrice: 275.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'service'
    },
    {
      id: '32',
      name: 'Scythe of Vitur',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Elite two-handed weapon from Theatre of Blood.',
      price: 950.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '33',
      name: 'Harmonised Nightmare Staff',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Powerful magic staff for fast spell casting.',
      price: 750.00,
      salePrice: 699.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'weapon'
    },
    {
      id: '34',
      name: 'Justiciar Armor Set',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'High-defense armor from Theatre of Blood.',
      price: 425.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'armor'
    },
    {
      id: '35',
      name: 'Raids 3 Supply Pack',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Complete supply pack for Tombs of Amascut.',
      price: 65.00,
      salePrice: 55.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'OSRS',
      itemType: 'consumable'
    },
    {
      id: '36',
      name: 'Praesul Codex',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Ancient prayer codex from Angel of Death.',
      price: 550.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'consumable'
    },
    {
      id: '37',
      name: 'Fractured Staff of Armadyl',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
      description: 'Best-in-slot magic weapon.',
      price: 1200.00,
      salePrice: 1099.99,
      isOnSale: true,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'weapon'
    },
    {
      id: '38',
      name: 'Swift Components Pack',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
      description: 'Rare invention components bundle.',
      price: 85.00,
      isOnSale: false,
      isInStock: true,
      gameType: 'RS3',
      itemType: 'consumable'
    },
    {
      id: '39',
      name: 'Val\'anyr Fragment Bundle',
      imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
      description: 'Legendary hammer fragments set.',
      price: 299.99,
      salePrice: 275.00,
      isOnSale: true,
      isInStock: true,
      gameType: 'WOW',
      itemType: 'weapon'
    },
    {
        id: '40',
        name: 'Dragon Dagger',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/6e9f4fb1-0ee2-41a9-8ed9-cee200127a9e',
        description: 'A powerful melee weapon for close combat.',
        price: 45.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '41',
        name: 'Bandos Chestplate',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/d4b6bd53-c47e-48da-aef0-8c6b91d734a4',
        description: 'High-level melee armor offering great protection.',
        price: 85.00,
        salePrice: 75.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '42',
        name: 'Super Combat Potion Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Bundle of combat-enhancing potions.',
        price: 35.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '43',
        name: 'Noxious Scythe',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful two-handed weapon with great reach.',
        price: 250.00,
        salePrice: 225.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '44',
        name: 'Torva Platebody',
            imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Elite-tier melee armor.',
        price: 180.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '45',
        name: 'Overload Potion Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Premium combat enhancement potions.',
        price: 65.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '46',
        name: 'Shadowmourne',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary battle axe of immense power.',
        price: 450.00,
        salePrice: 399.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '47',
        name: 'Celestial Plate Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Mythic-level protective armor set.',
        price: 299.99,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '48',
        name: 'Flask of Power Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Set of powerful combat and utility potions.',
        price: 25.00,
        salePrice: 20.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '49',
        name: 'Abyssal Whip',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Fast attacking melee weapon.',
        price: 95.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '50',
        name: 'Armadyl Godsword',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary godsword with devastating special attack.',
        price: 175.00,
        salePrice: 150.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
                    id: '51',
        name: 'Primordial Boots',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot melee boots.',
        price: 120.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '52',
        name: 'Divine Super Combat Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Enhanced combat potions with divine effects.',
        price: 45.00,
        salePrice: 35.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '53',
        name: 'Drygore Longsword',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'High-tier melee weapon for advanced combat.',
        price: 195.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '54',
        name: 'Malevolent Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Superior degradeable power armor.',
        price: 280.00,
        salePrice: 250.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '55',
        name: 'Elder Overload Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Supreme combat enhancement potions.',
        price: 85.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '56',
        name: 'Thunderfury',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary sword of the Windseeker.',
        price: 550.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '57',
        name: 'Tier 20 Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Classic raid tier armor set.',
        price: 375.00,
        salePrice: 325.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '58',
        name: 'Mythic+ Potion Kit',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Essential potions for high-level dungeons.',
        price: 40.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '59',
        name: 'Twisted Bow',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful bow effective against magical creatures.',
        price: 850.00,
        salePrice: 799.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '60',
        name: 'Ancestral Robe Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot magic armor.',
        price: 275.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '61',
        name: 'Raids Potion Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete set of raiding potions.',
        price: 55.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
                id: '62',
        name: 'Staff of Sliske',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful magic staff with special effects.',
        price: 420.00,
        salePrice: 375.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '63',
        name: 'Trimmed Masterwork Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot melee armor.',
        price: 450.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '64',
        name: 'Supreme Raid Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete pack of high-tier consumables.',
        price: 95.00,
        salePrice: 85.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '65',
        name: 'Frostmourne Replica',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary sword of the Lich King.',
        price: 750.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '66',
        name: 'Mythic Raid Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Current tier mythic raid armor.',
        price: 425.00,
        salePrice: 399.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '67',
        name: 'Raid Ready Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete set of raiding consumables.',
        price: 75.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '68',
        name: 'Eldritch Crossbow',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Elite ranged weapon with special effect.',
        price: 650.00,
        salePrice: 599.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '69',
        name: 'Inquisitor Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Powerful crush-bonus armor set.',
        price: 395.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '70',
        name: 'Infernal Cape Service',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Prestigious cape showing PvM mastery.',
        price: 299.99,
        salePrice: 275.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'service'
      },
      {
        id: '71',
        name: 'Scythe of Vitur',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Elite two-handed weapon from Theatre of Blood.',
        price: 950.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
                id: '72',
        name: 'Harmonised Nightmare Staff',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful magic staff for fast spell casting.',
        price: 750.00,
        salePrice: 699.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '73',
        name: 'Justiciar Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'High-defense armor from Theatre of Blood.',
        price: 425.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '74',
        name: 'Raids 3 Supply Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete supply pack for Tombs of Amascut.',
        price: 65.00,
        salePrice: 55.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '75',
        name: 'Praesul Codex',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Ancient prayer codex from Angel of Death.',
        price: 550.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '76',
        name: 'Fractured Staff of Armadyl',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot magic weapon.',
        price: 1200.00,
        salePrice: 1099.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '77',
        name: 'Swift Components Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Rare invention components bundle.',
        price: 85.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
                id: '78',
        name: 'Val\'anyr Fragment Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary hammer fragments set.',
        price: 299.99,
        salePrice: 275.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '79',
        name: 'Dragon Dagger',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/6e9f4fb1-0ee2-41a9-8ed9-cee200127a9e',
        description: 'A powerful melee weapon for close combat.',
        price: 45.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '80',
        name: 'Bandos Chestplate',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/d4b6bd53-c47e-48da-aef0-8c6b91d734a4',
        description: 'High-level melee armor offering great protection.',
        price: 85.00,
        salePrice: 75.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '81',
        name: 'Super Combat Potion Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Bundle of combat-enhancing potions.',
        price: 35.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '82',
        name: 'Noxious Scythe',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful two-handed weapon with great reach.',
        price: 250.00,
        salePrice: 225.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '83',
        name: 'Torva Platebody',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Elite-tier melee armor.',
        price: 180.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '84',
        name: 'Overload Potion Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Premium combat enhancement potions.',
        price: 65.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '85',
        name: 'Shadowmourne',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary battle axe of immense power.',
        price: 450.00,
        salePrice: 399.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '86',
        name: 'Celestial Plate Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Mythic-level protective armor set.',
        price: 299.99,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '87',
        name: 'Flask of Power Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Set of powerful combat and utility potions.',
        price: 25.00,
        salePrice: 20.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '88',
        name: 'Abyssal Whip',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Fast attacking melee weapon.',
        price: 95.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
            id: '89',
        name: 'Armadyl Godsword',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Legendary godsword with devastating special attack.',
        price: 175.00,
        salePrice: 150.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '90',
        name: 'Primordial Boots',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/d4b6bd53-c47e-48da-aef0-8c6b91d734a4',
        description: 'Best-in-slot melee boots.',
        price: 120.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '91',
        name: 'Divine Super Combat Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Enhanced combat potions with divine effects.',
        price: 45.00,
        salePrice: 35.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '92',
        name: 'Drygore Longsword',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'High-tier melee weapon for advanced combat.',
        price: 195.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '93',
        name: 'Malevolent Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Superior degradeable power armor.',
        price: 280.00,
        salePrice: 250.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '94',
        name: 'Elder Overload Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Supreme combat enhancement potions.',
        price: 85.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '95',
        name: 'Thunderfury',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary sword of the Windseeker.',
        price: 550.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '96',
        name: 'Tier 20 Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Classic raid tier armor set.',
        price: 375.00,
        salePrice: 325.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '97',
        name: 'Mythic+ Potion Kit',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Essential potions for high-level dungeons.',
        price: 40.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '98',
        name: 'Twisted Bow',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful bow effective against magical creatures.',
        price: 850.00,
        salePrice: 799.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '99',
        name: 'Ancestral Robe Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot magic armor.',
        price: 275.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
                id: '100',
        name: 'Raids Potion Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete set of raiding potions.',
        price: 55.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '101',
        name: 'Staff of Sliske',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful magic staff with special effects.',
        price: 420.00,
        salePrice: 375.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '102',
        name: 'Trimmed Masterwork Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot melee armor.',
        price: 450.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'armor'
      },
      {
        id: '103',
        name: 'Supreme Raid Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete pack of high-tier consumables.',
        price: 95.00,
        salePrice: 85.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '104',
        name: 'Frostmourne Replica',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary sword of the Lich King.',
        price: 750.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '105',
        name: 'Mythic Raid Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Current tier mythic raid armor.',
        price: 425.00,
        salePrice: 399.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'armor'
      },
      {
        id: '106',
        name: 'Raid Ready Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete set of raiding consumables.',
        price: 75.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'consumable'
      },
      {
        id: '107',
        name: 'Eldritch Crossbow',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Elite ranged weapon with special effect.',
        price: 650.00,
        salePrice: 599.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '108',
        name: 'Inquisitor Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Powerful crush-bonus armor set.',
        price: 395.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '109',
        name: 'Infernal Cape Service',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Prestigious cape showing PvM mastery.',
        price: 299.99,
        salePrice: 275.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'service'
      },
      {
        id: '110',
        name: 'Scythe of Vitur',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Elite two-handed weapon from Theatre of Blood.',
        price: 950.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
                id: '111',
        name: 'Harmonised Nightmare Staff',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Powerful magic staff for fast spell casting.',
        price: 750.00,
        salePrice: 699.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
      {
        id: '112',
        name: 'Justiciar Armor Set',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'High-defense armor from Theatre of Blood.',
        price: 425.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'armor'
      },
      {
        id: '113',
        name: 'Raids 3 Supply Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Complete supply pack for Tombs of Amascut.',
        price: 65.00,
        salePrice: 55.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'consumable'
      },
      {
        id: '114',
        name: 'Praesul Codex',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Ancient prayer codex from Angel of Death.',
        price: 550.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '115',
        name: 'Fractured Staff of Armadyl',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/dd0db023-7a63-4f7b-a164-97e16889668f',
        description: 'Best-in-slot magic weapon.',
        price: 1200.00,
        salePrice: 1099.99,
        isOnSale: true,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'weapon'
      },
      {
        id: '116',
        name: 'Swift Components Pack',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/821b2692-be44-4cfb-ac30-5c3067f70fa7',
        description: 'Rare invention components bundle.',
        price: 85.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'RS3',
        itemType: 'consumable'
      },
      {
        id: '117',
        name: 'Val\'anyr Fragment Bundle',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'Legendary hammer fragments set.',
        price: 299.99,
        salePrice: 275.00,
        isOnSale: true,
        isInStock: true,
        gameType: 'WOW',
        itemType: 'weapon'
      },
      {
        id: '118',
        name: 'Dragon Dagger',
        imageUrl: 'https://chicks-products.s3.amazonaws.com/e8f3850c-6efb-478b-b339-f8b58195fc05',
        description: 'A powerful melee weapon for close combat.',
        price: 45.00,
        isOnSale: false,
        isInStock: true,
        gameType: 'OSRS',
        itemType: 'weapon'
      },
  ];

  export { mockProducts };